repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: "python3 -m pytest -s -v"
        language: system
        pass_filenames: false
        stages: [commit]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c ".venv/bin/pip3 freeze > requirements.txt; git add requirements.txt"
        language: system
        pass_filenames: false
        stages: [commit]